version: '3.7'
services:
  app:
    image: library/postgres:13.2-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgres
    environment:
      - POSTGRES_RANDOM_ROOT_PASSWORD=yes
      - POSTGRES_DATABASE=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=9mREsvXDs9Gk89Ef
